name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: example
          MYSQL_DATABASE: project_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Load Secrets from GitHub
      run: |
        echo "MYSQL_USER=${{ secrets.MYSQL_USER }}" >> $GITHUB_ENV
        echo "MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}" >> $GITHUB_ENV
        echo "MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}" >> $GITHUB_ENV

    - name: 1. Environment Setup - Install MySQL Client
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Wait for MySQL to become ready
      run: |
        until mysqladmin ping -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" --silent; do
          echo "Waiting for MySQL..."
          sleep 3
        done

    - name: Create project_db if not exists
      run: mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" -e "CREATE DATABASE IF NOT EXISTS $MYSQL_DATABASE;"

    - name: 2. Initial Schema Deployment - Create ClimateData Table
      run: mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" < sql/01_create_climatedata.sql

    - name: 3. Schema Update - Add Humidity Column
      run: mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" < sql/02_add_humidity_column.sql

    - name: 4. Data Seeding - Insert Sample Climate Data
      run: mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" < sql/03_seed_climatedata.sql

    - name: 5. Concurrent Query Execution - Install Python Dependencies
      run: pip install mysql-connector-python

    - name: 5. Concurrent Query Execution - Run Python Script
      run: python3 scripts/multi_thread_queries.py

    - name: 6. Validation Step - Check Table, Column, Seeded Data, and Concurrent Execution Results
      run: |
        echo " Table structure:"
        mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; DESCRIBE ClimateData;"

        echo " All data:"
        mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; SELECT * FROM ClimateData;"

        echo " Verify update: humidity for Toronto"
        mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; SELECT humidity FROM ClimateData WHERE location='Toronto';"

        echo " Verify insert: Delhi"
        mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; SELECT * FROM ClimateData WHERE location='Delhi';"

        echo " Verify select: temperature > 20°C"
        mysql -h 127.0.0.1 -P 3306 -u$MYSQL_USER -p"$MYSQL_PASSWORD" -e "USE $MYSQL_DATABASE; SELECT * FROM ClimateData WHERE temperature > 20;"
