name: CI/CD Pipeline

on:
  push:
    branches: [ main ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: Rambo@123
          MYSQL_DATABASE: project_db
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: 1. Environment Setup - Install MySQL Client
      run: sudo apt-get update && sudo apt-get install -y mysql-client

    - name: Wait for MySQL to become ready
      run: |
        until mysqladmin ping -h 127.0.0.1 -P 3306 -uroot -pRambo@123 --silent; do
          echo "Waiting for MySQL..."
          sleep 3
        done

    - name: 2. Initial Schema Deployment - Create ClimateData Table
      run: mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 < sql/create_climatedata.sql

    - name: 3. Schema Update - Add Humidity Column
      run: mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 < sql/add_humidity.sql

    - name: 4. Data Seeding - Insert Sample Climate Data
      run: mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 < sql/seed_data.sql

    - name: 5. Concurrent Query Execution - Install Python Dependencies
      run: pip install mysql-connector-python

    - name: 5. Concurrent Query Execution - Run Python Script
      run: python3 scripts/multi_thread_queries.py

    - name: 6. Validation Step - Check Table, Column, Seeded Data, and Concurrent Execution Results
      run: |
        echo " Table structure:"
        mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 -e "USE project_db; DESCRIBE ClimateData;"

        echo " All data:"
        mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 -e "USE project_db; SELECT * FROM ClimateData;"

        echo " Verify update: humidity for Toronto"
        mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 -e "USE project_db; SELECT humidity FROM ClimateData WHERE location='Toronto';"

        echo " Verify insert: Delhi"
        mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 -e "USE project_db; SELECT * FROM ClimateData WHERE location='Delhi';"

        echo " Verify select: temperature > 20°C"
        mysql -h 127.0.0.1 -P 3306 -uroot -pRambo@123 -e "USE project_db; SELECT * FROM ClimateData WHERE temperature > 20;"
